apiVersion: v1
kind: Service
metadata:
  name: dashy-service
  namespace: monitoring
spec:
  selector:
    app: dashy
  ports:
  - name: dashy
    port: 8888

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dashy
  namespace: monitoring
spec:
  replicas: 1
  serviceName: dashy-service
  selector:
    matchLabels:
      app: dashy
  template:
    metadata:
      labels:
        app: dashy
    spec:
      containers:
        - name: dashy
          image: lissy93/dashy:2.1.1
          ports:
            - name: dashy
              containerPort: 8888
              protocol: TCP
          volumeMounts:
            # - name: dashy-data
            #   mountPath: /app/public
            - name: config-volume
              mountPath: /app/public/
          livenessProbe:
            tcpSocket:
              port: 8888
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /home
              port: 8888
            initialDelaySeconds: 5
            periodSeconds: 3              
   

  # volumeClaimTemplates:
  #   - metadata:
  #       name: dashy-data
  #     spec:
  #       accessModes: ["ReadWriteOnce"]
  #       volumeMode: Filesystem
  #       resources:
  #         requests:
  #           storage: 1Gi

      volumes:
      - name: config-volume
        configMap:
          name: dashy-config

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dashy-ingress
  namespace: monitoring
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - dashy.guiadodevops.com.br
    secretName: dashy-tls
  rules:
  - host: dashy.guiadodevops.com.br
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dashy-service
            port:
              number: 8888

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: dashy-config
data:
  conf.yml: |-
    # Page meta info, like heading, footer text and nav links
    pageInfo:
      title: Dashy
      description: Welcome to your new dashboard!
      navLinks:
      - title: GitHub
        path: https://github.com/Lissy93/dashy
      - title: Documentation
        path: https://dashy.to/docs

    # Optional app settings and configuration
    appConfig:
      theme: colorful

    # Main content - An array of sections, each containing an array of items
    sections:
    - name: Getting Started
      icon: fas fa-rocket
      items:
      - title: Dashy Live
        description: Development a project management links for Dashy
        icon: https://i.ibb.co/qWWpD0v/astro-dab-128.png
        url: https://live.dashy.to/
        target: newtab
      - title: GitHub
        description: Source Code, Issues and Pull Requests
        url: https://github.com/lissy93/dashy
        icon: favicon
      - title: Docs
        description: Configuring & Usage Documentation
        provider: Dashy.to
        icon: far fa-book
        url: https://dashy.to/docs
      - title: Showcase
        description: See how others are using Dashy
        url: https://github.com/Lissy93/dashy/blob/master/docs/showcase.md
        icon: far fa-grin-hearts
      - title: Config Guide
        description: See full list of configuration options
        url: https://github.com/Lissy93/dashy/blob/master/docs/configuring.md
        icon: fas fa-wrench
      - title: Support
        description: Get help with Dashy, raise a bug, or get in contact
        url: https://github.com/Lissy93/dashy/blob/master/.github/SUPPORT.md
        icon: far fa-hands-helping
