apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true 
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  source:
    path: kubernetes/infra/keycloak
    repoURL: https://github.com/wpalmeida/guiadodevops.git
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: security
  project: infra