# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: loki
#   namespace: argocd
# spec:
#   syncPolicy:
#     automated:
#       prune: true
#       allowEmpty: true 
#       selfHeal: true
#     syncOptions:
#     - CreateNamespace=true
#   source:
#     path: kubernetes/infra/loki
#     repoURL: https://github.com/wpalmeida/guiadodevops.git
#     targetRevision: HEAD
#   destination:
#     server: 'https://kubernetes.default.svc'
#     namespace: monitoring
#   project: infra