apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: conversor-moeda-app-nonprod
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true 
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  source:
    path: kubernetes/
    repoURL: https://github.com/wpalmeida/currencyconverter.git
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: conversor-moeda-app-nonprod
  project: nonprod