apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-nonprod
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true 
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  source:
    path: guestbook
    repoURL: https://github.com/kubernetes/examples.git
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: guestbook-nonprod
  project: nonprod