annotations:
  artifacthub.io/changes: |
    - kind: fixed
      description: "Fixed webhook install failure: `http-webhook-metrics: must be no more than 15 characters`. ([#4173](https://github.com/kubernetes-sigs/external-dns/pull/4173)) [@gabe565](https://github.com/gabe565)"
apiVersion: v2
appVersion: 0.14.0
description: ExternalDNS synchronizes exposed Kubernetes Services and Ingresses with
  DNS providers.
home: https://github.com/kubernetes-sigs/external-dns/
icon: https://github.com/kubernetes-sigs/external-dns/raw/master/docs/img/external-dns.png
keywords:
- kubernetes
- externaldns
- external-dns
- dns
- service
- ingress
maintainers:
- email: steve.hipwell@gmail.com
  name: stevehipwell
name: external-dns
sources:
- https://github.com/kubernetes-sigs/external-dns/
type: application
version: 1.14.1
