apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appofapps
  namespace: argocd     
spec:
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true 
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  source:
    path: kubernetes/infra/argocd/applications/applications
    repoURL: https://github.com/wpalmeida/guiadodevops.git
    targetRevision: HEAD
    directory:
      recurse: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  project: default